### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by StartForKillerMC** [sleirsgoevy/ps4jb#10]
[WARN] parse.c:2184: ps4jb/src/8cc/8cc/include/stdarg.h:1:1: type specifier missing, assuming int

[ERROR] parse.c:2214: ps4jb/src/8cc/8cc/include/stdarg.h:1:4: ';' or ',' are expected, but got /

**Comment by StartForKillerMC** [comment]
Anyways, it crash more when loading mira

**Comment by sleirsgoevy** [comment]
Parser errors are normal. If your code actually has errors then it's not a bug. Try compiling with gcc to see if there are any.

**Comment by StartForKillerMC** [comment]
I mean, i haven't touched anything, i cloned the repo and run make

**Comment by sleirsgoevy** [comment]
Then run the build with KEEPTEMP=1 and upload the /tmp/tmp.*/pp.c file (or check in MacOS-specific temp folders).

**Comment by StartForKillerMC** [comment]
I'm building it with WSL

**Comment by sleirsgoevy** [comment]
Then it's /tmp/tmp.*/pp.c inside the VM. Please upload that file here so I can investigate the issue.

**Comment by StartForKillerMC** [comment]
Here: https://pastebin.com/TRxAS1nf

**Comment by sleirsgoevy** [comment]
Interestingly enough this pp.c compiles fine for me. Does the error still appear? Are you sure you uploaded the right file?

You may also try replacing `cpp` with `gcc -E`, maybe that will give some more clue.

**Comment by StartForKillerMC** [comment]
Ow, my fault i've uploaded another file
here it's good: https://pastebin.com/KAeBwr4q

**Comment by sleirsgoevy** [comment]
This seems to be a bug with WSL. At line 4 you can see that the preprocessor read the file `freebsd-headers/stdint.h` as `sys/stdint.h`, while actually it is a symlink pointing there. So it basically read the link's path instead of the referred file.
Using WSL2 instead should solve the issue, as that uses a real Linux kernel under the hood.

**Comment by StartForKillerMC** [comment]
I'm using wsl2 i think

**Comment by StartForKillerMC** [comment]
Okay, removing and creating the symlinks works for me.

**Comment by sleirsgoevy** [comment]
Reopen if the issue remains.
