### ISSUE TITLE
Freezing issue

### ISSUE THREAD

**Issue by venom980** [sleirsgoevy/ps4jb#14]
Sir Errors are Fixed in Debug Setting.And No crashes But when we start game the game freezes nothing works not even controller

**Comment by StartForKillerMC** [comment]
What game is it?

**Comment by venom980** [comment]
Lost legacy, also someone said to me same thing that game freezes when we start

**Comment by StartForKillerMC** [comment]
Yeah, not a ps4js issue: [Refer to this](https://github.com/OpenOrbis/mira-project/issues/61)

**Comment by venom980** [comment]
Yes bro but other people also said me about freezing

**Comment by StartForKillerMC** [comment]
Then you need to wait until someone fixes it on the mira-project, 6.72 kernel patches are not developed here, this is only an entrypoint.

**Comment by venom980** [comment]
Mira have issues

**Comment by venom980** [comment]
You tried other games?

**Comment by sleirsgoevy** [comment]
Does it reproduce on the latest version?

**Comment by venom980** [comment]
No I’m hosting your jailbreak locally.it works perfect but on some games showing Ce-error

**Comment by Dominit86** [comment]
you must use MIRA noHB example DOA 6 with HB CE-34878-0 without working fine

**Comment by sleirsgoevy** [comment]
There is no need to host this thing locally, https://sleirsgoevy.github.io/ps4jb/ is served from this repository.

Reopen if the "freezing issue" persists.
