### ISSUE TITLE
OOB write from rdi_pivot

### ISSUE THREAD

**Issue by CelesteBlue-dev** [sleirsgoevy/ps4jb#16]
rdi_pivot size is initialized to 1:
https://github.com/sleirsgoevy/ps4jb/blob/da0bd9a3459dcb5356a83ccbb84acbc52289f91a/src/kex.c#L642
but rdi_pivot is written at offset 7:
https://github.com/sleirsgoevy/ps4jb/blob/da0bd9a3459dcb5356a83ccbb84acbc52289f91a/src/kex.c#L644
Krop runs nevertheless but that might corrupt some ROP data.

**Comment by sleirsgoevy** [comment]
Does not make sense anymore. The current version does not run kROP at all.
