### ISSUE TITLE
DarkModderVC is profiting from your work

### ISSUE THREAD

**Issue by PaulJenkin** [sleirsgoevy/ps4jb#24]
The developer / copier  (DarkModderVC) is just copying your c-code.js file whenever you update it. He includes this file in his repository and claiming its more stable than your release

All he is doing is 
1. take your c-code.js
2. remove the comments 
3. Split them into 5 files
4. Instead of using HTML as fronted, he is using javascript

Note: so far he has received around $430  in donations using PSXHAX forum

I also have discussed the same with PSXHAX forum admin about this, 
They have replied that if your are Ok with his claim, they will continue recognise Darkmodders work separately else, there will one thread related to your work (which will include Darkmodders work as side note)

If at all you are planning to take donations, Please share your paypal / Kofi links so that we can add it in PSXHAX

His Github page
https://github.com/DarkModderVC/PS4JB

i know that you are working on many thing which all are thankful for, I just reached out to you since it was hard to digest that some one is shadowing your work and getting all the credits

**Comment by kachijs** [comment]
> The developer / copier (DarkModderVC) is just copying your c-code.js file whenever you update it. He includes this file in his repository and claiming its more stable than your release

From my experience @DarkModderVC's release at the moment is more stable than @sleirsgoevy stable release. I don't know how or why but this is from my experience.

**Comment by PaulJenkin** [comment]
@kachijs DarkModderVC was never stable than @sleirsgoevy because the Jb code was always same (except the file size was reduced only by removing comments)

Since it was unstable release there was no way verify which more stable. it may work at a time and may not work at a time.

DarkModderVC took this as advantage and in all forum created a mirage like, he done something better than @sleirsgoevy.
Also started taking donation for this copying work. 

Now half of the people in the Scene thinks DarkModderVC as developer who has made a stable implementation. 
This will all be cleared, **if @sleirsgoevy can call out this.**

I believe the @sleirsgoevy should get all the credit for this work and it should not go to the person who copied this (DarkModderVC)

**Comment by cypheron** [comment]
I fully agree with @PaulJenkin. Other than the aforementioned changes there's nothing that could improve the stability. The user is a front-end dev who was just really clever to set up a donations link based on an unproven claim. All reports on stability may as well be fake as many GitHub accounts commenting where just newly created or have no prior history.
DarkModderVC also explained in issue #23 that his "mod" no longer has any benefits other than being offline cache-able.

**Comment by PaulJenkin** [comment]
Closing the issue as there is no response from @sleirsgoevy
