### ISSUE TITLE
Crash on Rest mode

### ISSUE THREAD

**Issue by indraAsLesmana** [sleirsgoevy/ps4jb#28]
When position is in Rest Mode, then I want to turn on.. can not turn on, it freeze does not appear at all on the screen. sometime power like shutdown.

**Comment by neamat-ar** [comment]
My ps4 first black and white screen then crashes no display after after that I have to turn it on again  second time freeze white screen

**Comment by Elbek1997** [comment]
Try putting rest mode with all applications closed. For now it seems to work well.

**Comment by indraAsLesmana** [comment]
Yes its working now. thanks.
