### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by PaulJenkin** [sleirsgoevy/ps4jb#33]
I am getting the below error, while doing a Make from Src

[WARN] parse.c:2184: ps4jb/src/8cc/8cc/include/stdarg.h:1:1: type specifier missing, assuming int

[ERROR] parse.c:2214: ps4jb/src/8cc/8cc/include/stdarg.h:1:4: ';' or ',' are expected, but got /

Note: i see that some other user also have had the same error, it was resolved by removing simlinks.
In my case i am not sure on how to resolve this.
Any help would be appreciated

I am using : linux

**Comment by StartForKillerMC** [comment]
Yes, the repo have bad symlinks, just searchs for text files that seems to be symlinks, and recreate the symlinks

**Comment by PaulJenkin** [comment]
@StartForKillerMC 
tried searching for symlinks, was not able to find any
Can give me the the **file path**

**Comment by StartForKillerMC** [comment]
I think, for example, the file that is failing for you is a symlink

**Comment by PaulJenkin** [comment]
@StartForKillerMC
Will it possible to give the exact the file name and file path, which needs to be modified.

Sorry for asking these repeated questions, If i can fix this issue. i can start playing around with kex file

**Comment by StartForKillerMC** [comment]
There are many broken symlinks, it isn't only one, I can give examples but if you want you can type the command "ls -l" and it will show you the different files. If you open it throught VSCode you can see the files that don't match

**Comment by PaulJenkin** [comment]
@StartForKillerMC
I have replace the freebsd-headers using freebsd-headers from openorbis project "https://github.com/OpenOrbis/freebsd-headers"

Now i am getting the below
'''
Traceback (most recent call last):
  File "8cc/bad_hoist/rop/compiler.py", line 83, in <module>
    print(main(*sys.argv[1:]))
  File "8cc/bad_hoist/rop/compiler.py", line 80, in main
    return final_pass(asm, labels, gadgets)
  File "8cc/bad_hoist/rop/compiler.py", line 64, in final_pass
    raise SyntaxError(i)
SyntaxError: mov [rax], rdi
make: *** [Makefile:11: build/oldjb/c-code.js] Error 1
'''

**Comment by sleirsgoevy** [comment]
I fucked up. I pushed the fixes into a submodule and forgot to update the submodule to point to master.

Regarding the SyntaxError: have you successfully dumped all 28-or-so megabytes of WebKit?

**Comment by PaulJenkin** [comment]
@sleirsgoevy 
With the New code i re dumped the webkit and I am able to generate c-code.js file.
Now its working fine
Thanks a lot

Please close this issue , once you have read this
