### ISSUE TITLE
Todex payload

### ISSUE THREAD

**Issue by chronoss09** [sleirsgoevy/ps4jb#35]
It's not an issue but can u add a Todex payload for users who have error ce-30391-6 ?

Here are the thread : https://www.psxhax.com/threads/ps4-6-72-5-05-payload-to-unlock-debug-features-fpkg-game-trophies.7685/

**Comment by PaulJenkin** [comment]
@chronoss09 
I have Created a pull requested to add this functionality
https://github.com/sleirsgoevy/ps4jb/pull/43

lets see if sleirsgoevy is accepting this

**Comment by PaulJenkin** [comment]
Please Close the issue to dex payload has been added
