### ISSUE TITLE
External HDD issue

### ISSUE THREAD

**Issue by ShahdadLTF** [sleirsgoevy/ps4jb#40]
Thank you so much for your outstanding job. There is an issue with the Mira+Hen. If you have a usb external hdd attached as an external storage for game installs, the games does not work from the external storage. This is quite an important issue to be resolved!

**Comment by ShahdadLTF** [comment]
Just to add, the problem is with whatever payload

**Comment by sleirsgoevy** [comment]
If you can't **install** games using Debug Settings, check that you external hard drive is formatted into **FAT32 or exFAT**, not NTFS or some other filesystem. If the game installs (i.e. you can see the icon on the homescreen) but does not run, then this is most probably a [Mira bug](https://github.com/OpenOrbis/mira-project/issues) and you should report the bug there.

**Comment by ShahdadLTF** [comment]
The format is ok. I managed to find a work around using app2usb instead of using the ps4 native internal>external transfer.
