### ISSUE TITLE
fakeusb working on the wrong way

### ISSUE THREAD

**Issue by A7moo7y** [sleirsgoevy/ps4jb#56]
When I move to package installer only pkgs on my usb stick are shown but not the pkg on the fakeusb directory. 
I use ps4 explorer to take a look and I found that files from fakeusb directory shows on usb1 folder in mnt and my usb drive files still on usb0. I restarted my ps4 and run the payload again and again but the files only move from fakeusb to usb1 how can I solve that ?
Note* (My ps4 slim have only 1 working usb port)

**Comment by sleirsgoevy** [comment]
You **first** insert the stick, **then** you run the payload. This way it works. The other way round it doesn't.

Anyway, this is a hack. Try using [this](https://github.com/sleirsgoevy/hbstore-cdn) instead.

**Comment by A7moo7y** [comment]
Yes I did but the same problem the files show on usb1 only, the usb0 contains my real usb files, also I have one new file (usb1_real) .
My usb is formatted as exfat and its working fine can you help me to get this work I really need it!
