### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by tomservo84** [sleirsgoevy/ps4jb#58]
I'm trying to compile your jb from source on a Linux server.  I've got python 3.7.5, ROPgadget v6.3, my PS4 is running 6.72.

When trying to work with the gadgets.txt file, I get the following error:

    8cc/8cc/python/rop-ps4-8cc /dev/stdout 8cc/librop/.c printf_stub.c 8cc/ps4/.c oldkex.c | python3 8cc/bad_hoist/rop/compiler.py /dev/stdin 8cc/bad_hoist/dumps/gadgets.txt > build/oldjb/c-code.js
    Traceback (most recent call last):
    File "8cc/bad_hoist/rop/compiler.py", line 149, in <module>
    print(main(*sys.argv[1:]))
    File "8cc/bad_hoist/rop/compiler.py", line 146, in main
    return final_pass(asm, labels, gadgets)
    File "8cc/bad_hoist/rop/compiler.py", line 107, in final_pass
    raise SyntaxError(i)
    SyntaxError: mov [rax], rdi
    make: *** [Makefile:13: build/oldjb/c-code.js] Error 1

I've uploaded my gadgets.txt file here:

https://drive.google.com/file/d/1whWO2dIq3spzV3pwC6frf5gNWz3be7cn/view?usp=sharing

I'm not sure if I'm missing something, maybe a python library?

**Comment by sleirsgoevy** [comment]
Probably your library dumps are truncated. My `gadgets.txt` has 1058518 lines, while yours only has 93079 lines. Make sure you have a non-faulty network connection.

For reference: my `webkit.bin` is 26259455 bytes long, and the `mov [rax], rdi` gadget is at `webkit_base+0xdcaa77`.

**Comment by tomservo84** [comment]
Wow...yes...something is definitely not right.  My webkit.bin is 278,527...1% of the proper size.  I can't tonight but I will try again tomorrow...and instead of using the wifi I will try wired.

**Comment by tomservo84** [comment]
That was it!  I hooked up to wired connection, and all worked as it was supposed to.  I just never realized that the size of those files was too small.

Thanks so much!

**Comment by tomservo84** [comment]
Please close this

**Comment by sleirsgoevy** [comment]
AFAIK you could've closed this yourself.
