### ISSUE TITLE
FAKEUSB doesn't work.

### ISSUE THREAD

**Issue by nkrapivin** [sleirsgoevy/ps4jb#60]
I've copied the pkg in `/user/home/fakeusb` but Package Installer doesn't see anything.

Really annoying since regular Mira breaks Remote PKG Installer...

**Comment by sleirsgoevy** [comment]
Insert your drive, go to "Debug settings", you won't see your pkg. Then activate FAKEUSB and go to "Debug Settings" again.

**Comment by sleirsgoevy** [comment]
Anyway, I am going to soon upload another payload for local PKG installation (essentially R.P.I. as a payload).

**Comment by nkrapivin** [comment]
> Insert your drive, go to "Debug settings", you won't see your pkg. Then activate FAKEUSB and go to "Debug Settings" again.

any usb drive I suppose? :)

**Comment by sleirsgoevy** [comment]
Any USB drive that is recognized by the system. It doesn't need to contain any specific files or folders.

**Comment by nkrapivin** [comment]
> Insert your drive, go to "Debug settings", you won't see your pkg. Then activate FAKEUSB and go to "Debug Settings" again.

this worked, but it's more of a "костыль" than a solution :)

**Comment by sleirsgoevy** [comment]
I know, but as I just said I'm going to upload a specialized payload for local package installation, based on [this flatz' writeup](https://flatz.github.io/).

**Comment by Brutal-sam** [comment]
@sleirsgoevy any possibility to port fakeusb to 7.02 and above?

**Comment by sleirsgoevy** [comment]
@Brutal-sam it should work as is. It just does not have a link on 7.02 homepage.
