### ISSUE TITLE
Linux payload of 6.72 doesn't work.

### ISSUE THREAD

**Issue by harshdhaliwal5103** [sleirsgoevy/ps4jb#68]
I am on 6.72 PS4 Slim CUH-2108B Belize model.
Your linux payload doesn't work neither for usb nor for files in user/system/boot/.
Linux from other host (Leeful) works which implies there is no problem in my console.
But I want to boot it internally by keeping files in user/system/boot and only your host boot from it, but no longer.
If I run JB->Mira->Linux, then it is infinite loading screen which eventually crashes system
If I run JB->Linux, then it either kernel panics ir crashes or infinite loading screen.
This is on 6.72.
On 7.02 everything is fine.
I hope you will look into it and fix it as soon as possible.
Thanks

**Comment by sleirsgoevy** [comment]
Fixed.

**Comment by harshdhaliwal5103** [comment]
> Fixed.

Thanks ;)

**Comment by harshdhaliwal5103** [comment]
> Fixed.

By the way, can you tell what the problem was?

**Comment by sleirsgoevy** [comment]
I accidentially embedded a 7.02 ps4-kexec binary inside the 6.72 payload.

**Comment by harshdhaliwal5103** [comment]
> I accidentially embedded a 7.02 ps4-kexec binary inside the 6.72 payload.

After you fixed it, no black screen or crash.
Perfect for loading linux from USB.
For internal, it only detect bzImage and initramfs.cpio.gz, not psxitarch.tar.xz .
You have to keep psxitarch.tar.xz in USB for installation.
Is it what it usually do?
After installation, will it boot from internal HDD without USB?
I also saw your main.c in ps4jb/src/payloads/linux and it doesn't mention psxitarch.tar.xz

**Comment by 0792880792** [comment]
**********72

**Comment by 0792880792** [comment]
**********

**Comment by amirsitro** [comment]
Thanks
