### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by harshdhaliwal1** [sleirsgoevy/ps4jb#79]
Got kernel offsets and dumped webkit.bin on 7.55, will it help?

**Comment by matheussurf24** [comment]
Мы работаем над 7.51 с хорошими результатами, так что давайте работать над 7.55, всем помогите и добро пожаловать, у вас есть ссылка?

**Comment by harshdhaliwal1** [comment]
I will share link in some time as I fully finish with dumping on 7.55, by the way what stage of 7.51 are you on?

**Comment by matheussurf24** [comment]
Хорошо, я не знаю, какой%, но мы очень оптимистично смотрим на результат, у вас есть ссылка?

**Comment by therootlord** [comment]
Hey, just informing, rop is working on 7.51, are there anything i could help with? 
![IMG_20210208_165433137](https://user-images.githubusercontent.com/16946825/107277459-4e617280-6a4c-11eb-8a27-71bdaf8829d8.jpg)

**Comment by matheussurf24** [comment]
сделайте ссылку и пришлите мне пожалуйста

**Comment by harshdhaliwal1** [comment]
I will upload it full after i dump adresses, just wait
