### ISSUE TITLE
Question about RAM and VRAM system (Linux)

### ISSUE THREAD

**Issue by gabriel-maxx** [sleirsgoevy/ps4jb#87]
hello I would like to know if we can use the maximum potential of the ps4 on linux, I say this because everywhere I searched they said that the ps4 has 8gb ram, but after testing many games with orbistoolbox I noticed that some games the ps4 adjusts the dimension for ex : 8192-ram 2560-vram,10240-ram 4096-vram, I'm talking about the slim not the pro, so could you explain this to me better? i'm confused can we have 10gb ram and 4gb vram on linux?

could you increase the vram limit from 5gb to 10gb? god of war changes vram dimension to 10gb while keeping ram at 6gb...

**Comment by sleirsgoevy** [comment]
This setting is currently broken for any RAM sizes above 3GB. And it is technically impossible to go above 8GB, as this memory is part of the normal ram of which the PS4 has only 8GB.

**Comment by gabriel-maxx** [comment]
> This setting is currently broken for any RAM sizes above 3GB. And it is technically impossible to go above 8GB, as this memory is part of the normal ram of which the PS4 has only 8GB.

it's not broken I used 4gb vram several times and it works perfectly, and also some games showed that ps4 has 16gb of memory through orbistoolbox and not 8gb, could you explain this to me please?
